### ISSUE TITLE
Add controller, view, model, factory and repository in the correct folders

### ISSUE THREAD

**Issue by snyhde** [PentiaLabs/generator-helix#24] opened 2017-01-31 15:56 UTC
Add a "<ProjectName>Controller.cs" in the /Controllers folder and let it inherit from System.web.mvc.controller, and create a dummy ActionResult method, dummy poco view model, dummy factory and a dummy repository and let the repository get the view model in the controller and create a dummy view model and output some simple data in the view. So it is all hooked up nice and simple.

**Comment by TakeitEasyAlan** [comment] 2017-01-31 19:37
@Hafeok I don't believe we should start to add classes, etc.

It could be another generator ? i.e generator-addsitecoremvc?

**Comment by soen** [comment] 2017-02-12 00:02
Possibly a duplicate of #23 ?

**Comment by Hafeok** [comment] 2017-02-21 13:58
Closing this - this can now be done using the new template feature. See issue #2 and the documentation has been updated :)

**Closed as completed by Hafeok** 2017-02-21 13:58 UTC
