### ISSUE TITLE
Target data store in serialization.config incorrect

### ISSUE THREAD

**Issue by eriktbe** [PentiaLabs/generator-helix#104] opened 2017-07-20 11:24 UTC
### User story
As a developer, I want the target data store in the serialization.config set to the correct folder so that items are serialized in the correct location.

### Expected behavior
When generating a new project, the target data store in the serialization.config is set to '$(sourceFolder)\[Layer]\[Module]\serialization'

### Actual behavior
When generating a new project, the target data store in the serialization.config is set to '$(projectFolder)\[Module]\$(configurationFolder)'

### Steps to reproduce the behavior

Run yo helix:add

**Comment by TakeitEasyAlan** [comment] 2017-08-25 11:14
I don't believe this is a bug, if the format does not meet your specific requirements, you can overwrite the template for the serilisation.config.

@eriktbe $(featureFolder) - is the root folder for the feature layer, then a sub folder with the [Module] name is created.

i.e. [Layer]\[Module] 

$(configurationFolder) - is an additional layer is required as single module can have a number of configurations, so an additional folder is required 

i.e. you could have a template, master, layouts, dictionary item, etc. For example dictionary items will have configuration which is deploy once.

So I believe the file is created correctly.

**Comment by Saturate** [comment] 2018-04-04 13:18
Closing ad @TakeitEasyAlan said wontfix

**Closed as completed by Saturate** 2018-04-04 13:18 UTC
Labels: wontfix

**Comment by TakeitEasyAlan** [comment] 2018-04-05 07:46
well I said that iti s not a bug, if it was i would fix it :)
